### PR TITLE
added logo to readme.md

### PR DESCRIPTION
**Pull request by jjharmsy**
There are two problems I see with this right now.

1.) The link to the PNG is long as fuck in the Readme.md file

2.) When you actually display how the read me renders in vscode it will display the logo, but on github it just has a shitty little link.

### CODE REVIEW

**Comment by jjharmsy** [comment]
I also added a rule that you have to PR to merge stuff and it needs at least one approval

**Comment by jjharmsy** [comment]
I fixed the issues I was having above^^. I made the logo in 0.2 seconds and it will def change later but i thought it would be good to have a placeholder for now.

**Comment by bcain150** [comment]
I think you can also add me as a reviewer automatically in settings. Rn it says that there are no reviewers requested. I think I get a notif if I'm a reviewer.

**Comment by bcain150** [comment]
Dude that logo is actually incredible.

**Review by bcain150 — APPROVED** [review]
He's done it

**Pull request merged**
